# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/BulkWaterMeterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BulkWaterMeterDialog(object):
    def setupUi(self, BulkWaterMeterDialog):
        BulkWaterMeterDialog.setObjectName("BulkWaterMeterDialog")
        BulkWaterMeterDialog.resize(588, 400)
        BulkWaterMeterDialog.setMinimumSize(QtCore.QSize(588, 400))
        BulkWaterMeterDialog.setMaximumSize(QtCore.QSize(588, 400))
        self.buttonBox = QtWidgets.QDialogButtonBox(BulkWaterMeterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 360, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(BulkWaterMeterDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.meter_number_edit = QtWidgets.QLineEdit(self.tab)
        self.meter_number_edit.setGeometry(QtCore.QRect(25, 30, 196, 20))
        self.meter_number_edit.setObjectName("meter_number_edit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(25, 15, 126, 16))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(25, 235, 126, 16))
        self.label_7.setObjectName("label_7")
        self.inspection_intervall_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(25, 162, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName("inspection_intervall_unit_cbox")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 190, 126, 16))
        self.label_15.setObjectName("label_15")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(270, 16, 126, 16))
        self.label_21.setObjectName("label_21")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 146, 126, 16))
        self.label_14.setObjectName("label_14")
        self.installation_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(25, 75, 26, 17))
        self.installation_date_chbox.setText("")
        self.installation_date_chbox.setObjectName("installation_date_chbox")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(25, 55, 126, 16))
        self.label_3.setObjectName("label_3")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 205, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.date_of_last_inspection_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(25, 210, 26, 17))
        self.date_of_last_inspection_chbox.setText("")
        self.date_of_last_inspection_chbox.setObjectName("date_of_last_inspection_chbox")
        self.inspection_intervall_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(25, 115, 196, 22))
        self.inspection_intervall_sbox.setObjectName("inspection_intervall_sbox")
        self.date_of_last_inspection_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(50, 205, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName("date_of_last_inspection_edit")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(25, 190, 126, 16))
        self.label_13.setObjectName("label_13")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(295, 31, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(25, 250, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.installation_date_edit = QtWidgets.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(50, 70, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName("installation_date_edit")
        self.height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(270, 160, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName("height_sbox")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(25, 100, 126, 16))
        self.label_5.setObjectName("label_5")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(270, 36, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(25, 145, 126, 16))
        self.label_6.setObjectName("label_6")
        self.meter_class_cbox = QtWidgets.QComboBox(self.tab)
        self.meter_class_cbox.setGeometry(QtCore.QRect(270, 71, 196, 22))
        self.meter_class_cbox.setObjectName("meter_class_cbox")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 56, 126, 16))
        self.label_9.setObjectName("label_9")
        self.meter_type_cbox = QtWidgets.QComboBox(self.tab)
        self.meter_type_cbox.setGeometry(QtCore.QRect(270, 116, 196, 22))
        self.meter_type_cbox.setObjectName("meter_type_cbox")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(270, 101, 126, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(BulkWaterMeterDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(BulkWaterMeterDialog.accept)
        self.buttonBox.rejected.connect(BulkWaterMeterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BulkWaterMeterDialog)
        BulkWaterMeterDialog.setTabOrder(self.tabWidget, self.meter_number_edit)
        BulkWaterMeterDialog.setTabOrder(self.meter_number_edit, self.installation_date_chbox)
        BulkWaterMeterDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        BulkWaterMeterDialog.setTabOrder(self.installation_date_edit, self.inspection_intervall_sbox)
        BulkWaterMeterDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        BulkWaterMeterDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        BulkWaterMeterDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        BulkWaterMeterDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        BulkWaterMeterDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        BulkWaterMeterDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        BulkWaterMeterDialog.setTabOrder(self.status_change_date_edit, self.meter_class_cbox)
        BulkWaterMeterDialog.setTabOrder(self.meter_class_cbox, self.meter_type_cbox)
        BulkWaterMeterDialog.setTabOrder(self.meter_type_cbox, self.height_sbox)
        BulkWaterMeterDialog.setTabOrder(self.height_sbox, self.network_cbox)

    def retranslateUi(self, BulkWaterMeterDialog):
        _translate = QtCore.QCoreApplication.translate
        BulkWaterMeterDialog.setWindowTitle(_translate("BulkWaterMeterDialog", "Add / Edit Bulk Water Meter"))
        self.label.setText(_translate("BulkWaterMeterDialog", "Meter Number"))
        self.label_7.setText(_translate("BulkWaterMeterDialog", "Operating State"))
        self.label_15.setText(_translate("BulkWaterMeterDialog", "Network"))
        self.label_21.setText(_translate("BulkWaterMeterDialog", "Date of Status Change"))
        self.label_14.setText(_translate("BulkWaterMeterDialog", "Height [m]"))
        self.label_3.setText(_translate("BulkWaterMeterDialog", "Installation Date"))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("BulkWaterMeterDialog", "yyyy-MM-dd"))
        self.label_13.setText(_translate("BulkWaterMeterDialog", "Date of Last Inspection"))
        self.status_change_date_edit.setDisplayFormat(_translate("BulkWaterMeterDialog", "yyyy-MM-dd"))
        self.installation_date_edit.setDisplayFormat(_translate("BulkWaterMeterDialog", "yyyy-MM-dd"))
        self.label_5.setText(_translate("BulkWaterMeterDialog", "Inspection Interval"))
        self.label_6.setText(_translate("BulkWaterMeterDialog", "Inspection Interval Unit"))
        self.label_9.setText(_translate("BulkWaterMeterDialog", "Meter Class"))
        self.label_10.setText(_translate("BulkWaterMeterDialog", "Meter Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("BulkWaterMeterDialog", "Description"))

from . import resources_rc
