# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/CustomerManagementForm.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomerManagementForm(object):
    def setupUi(self, CustomerManagementForm):
        CustomerManagementForm.setObjectName("CustomerManagementForm")
        CustomerManagementForm.resize(553, 388)
        self.unassign_cust_button = QtWidgets.QPushButton(CustomerManagementForm)
        self.unassign_cust_button.setGeometry(QtCore.QRect(290, 205, 25, 25))
        self.unassign_cust_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/wnt/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.unassign_cust_button.setIcon(icon)
        self.unassign_cust_button.setObjectName("unassign_cust_button")
        self.assigned_cust_twidget = QtWidgets.QTableWidget(CustomerManagementForm)
        self.assigned_cust_twidget.setGeometry(QtCore.QRect(15, 235, 526, 141))
        self.assigned_cust_twidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.assigned_cust_twidget.setAlternatingRowColors(True)
        self.assigned_cust_twidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.assigned_cust_twidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.assigned_cust_twidget.setObjectName("assigned_cust_twidget")
        self.assigned_cust_twidget.setColumnCount(8)
        self.assigned_cust_twidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.assigned_cust_twidget.setHorizontalHeaderItem(7, item)
        self.assign_cust_button = QtWidgets.QPushButton(CustomerManagementForm)
        self.assign_cust_button.setGeometry(QtCore.QRect(255, 205, 25, 25))
        self.assign_cust_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/wnt/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.assign_cust_button.setIcon(icon1)
        self.assign_cust_button.setObjectName("assign_cust_button")
        self.label_16 = QtWidgets.QLabel(CustomerManagementForm)
        self.label_16.setGeometry(QtCore.QRect(15, 220, 136, 16))
        self.label_16.setObjectName("label_16")
        self.registered_cust_twidget = QtWidgets.QTableWidget(CustomerManagementForm)
        self.registered_cust_twidget.setGeometry(QtCore.QRect(15, 80, 526, 121))
        self.registered_cust_twidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.registered_cust_twidget.setAlternatingRowColors(True)
        self.registered_cust_twidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.registered_cust_twidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.registered_cust_twidget.setObjectName("registered_cust_twidget")
        self.registered_cust_twidget.setColumnCount(8)
        self.registered_cust_twidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.registered_cust_twidget.setHorizontalHeaderItem(7, item)
        self.label_17 = QtWidgets.QLabel(CustomerManagementForm)
        self.label_17.setGeometry(QtCore.QRect(15, 65, 171, 16))
        self.label_17.setObjectName("label_17")
        self.search_term_edit = QtWidgets.QLineEdit(CustomerManagementForm)
        self.search_term_edit.setGeometry(QtCore.QRect(140, 30, 176, 20))
        self.search_term_edit.setObjectName("search_term_edit")
        self.label_18 = QtWidgets.QLabel(CustomerManagementForm)
        self.label_18.setGeometry(QtCore.QRect(140, 15, 171, 16))
        self.label_18.setObjectName("label_18")
        self.search_button = QtWidgets.QPushButton(CustomerManagementForm)
        self.search_button.setGeometry(QtCore.QRect(320, 27, 25, 25))
        self.search_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/wnt/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon2)
        self.search_button.setObjectName("search_button")
        self.id_rbutton = QtWidgets.QRadioButton(CustomerManagementForm)
        self.id_rbutton.setGeometry(QtCore.QRect(20, 15, 82, 17))
        self.id_rbutton.setChecked(False)
        self.id_rbutton.setObjectName("id_rbutton")
        self.buttonGroup = QtWidgets.QButtonGroup(CustomerManagementForm)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.id_rbutton)
        self.name_rbutton = QtWidgets.QRadioButton(CustomerManagementForm)
        self.name_rbutton.setGeometry(QtCore.QRect(20, 35, 82, 17))
        self.name_rbutton.setChecked(True)
        self.name_rbutton.setObjectName("name_rbutton")
        self.buttonGroup.addButton(self.name_rbutton)

        self.retranslateUi(CustomerManagementForm)
        QtCore.QMetaObject.connectSlotsByName(CustomerManagementForm)
        CustomerManagementForm.setTabOrder(self.id_rbutton, self.name_rbutton)
        CustomerManagementForm.setTabOrder(self.name_rbutton, self.search_term_edit)
        CustomerManagementForm.setTabOrder(self.search_term_edit, self.search_button)
        CustomerManagementForm.setTabOrder(self.search_button, self.registered_cust_twidget)
        CustomerManagementForm.setTabOrder(self.registered_cust_twidget, self.assign_cust_button)
        CustomerManagementForm.setTabOrder(self.assign_cust_button, self.unassign_cust_button)
        CustomerManagementForm.setTabOrder(self.unassign_cust_button, self.assigned_cust_twidget)

    def retranslateUi(self, CustomerManagementForm):
        _translate = QtCore.QCoreApplication.translate
        CustomerManagementForm.setWindowTitle(_translate("CustomerManagementForm", "Form"))
        self.unassign_cust_button.setToolTip(_translate("CustomerManagementForm", "Unassign Customer"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CustomerManagementForm", "ID"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CustomerManagementForm", "Name"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CustomerManagementForm", "Address"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(3)
        item.setText(_translate("CustomerManagementForm", "House No"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(4)
        item.setText(_translate("CustomerManagementForm", "City"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(5)
        item.setText(_translate("CustomerManagementForm", "CAN"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(6)
        item.setText(_translate("CustomerManagementForm", "Status"))
        item = self.assigned_cust_twidget.horizontalHeaderItem(7)
        item.setText(_translate("CustomerManagementForm", "Tariff Category"))
        self.assign_cust_button.setToolTip(_translate("CustomerManagementForm", "Assign Customer"))
        self.label_16.setText(_translate("CustomerManagementForm", "Assigned Customer(s)"))
        item = self.registered_cust_twidget.horizontalHeaderItem(0)
        item.setText(_translate("CustomerManagementForm", "ID"))
        item = self.registered_cust_twidget.horizontalHeaderItem(1)
        item.setText(_translate("CustomerManagementForm", "Name"))
        item = self.registered_cust_twidget.horizontalHeaderItem(2)
        item.setText(_translate("CustomerManagementForm", "Address"))
        item = self.registered_cust_twidget.horizontalHeaderItem(3)
        item.setText(_translate("CustomerManagementForm", "House No"))
        item = self.registered_cust_twidget.horizontalHeaderItem(4)
        item.setText(_translate("CustomerManagementForm", "City"))
        item = self.registered_cust_twidget.horizontalHeaderItem(5)
        item.setText(_translate("CustomerManagementForm", "CAN"))
        item = self.registered_cust_twidget.horizontalHeaderItem(6)
        item.setText(_translate("CustomerManagementForm", "Status"))
        item = self.registered_cust_twidget.horizontalHeaderItem(7)
        item.setText(_translate("CustomerManagementForm", "Tariff Category"))
        self.label_17.setText(_translate("CustomerManagementForm", "Registered Customer(s)"))
        self.label_18.setText(_translate("CustomerManagementForm", "Search Term"))
        self.search_button.setToolTip(_translate("CustomerManagementForm", "Add Damage"))
        self.id_rbutton.setText(_translate("CustomerManagementForm", "ID / CAN"))
        self.name_rbutton.setText(_translate("CustomerManagementForm", "Name"))

from . import resources_rc
