# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/DistributionPointDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DistributionPointDialog(object):
    def setupUi(self, DistributionPointDialog):
        DistributionPointDialog.setObjectName("DistributionPointDialog")
        DistributionPointDialog.resize(588, 460)
        DistributionPointDialog.setMinimumSize(QtCore.QSize(588, 460))
        DistributionPointDialog.setMaximumSize(QtCore.QSize(588, 460))
        self.buttonBox = QtWidgets.QDialogButtonBox(DistributionPointDialog)
        self.buttonBox.setGeometry(QtCore.QRect(355, 425, 216, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(DistributionPointDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.inspection_intervall_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(20, 115, 196, 22))
        self.inspection_intervall_sbox.setObjectName("inspection_intervall_sbox")
        self.installation_date_edit = QtWidgets.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 75, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName("installation_date_edit")
        self.installation_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 80, 26, 17))
        self.installation_date_chbox.setText("")
        self.installation_date_chbox.setObjectName("installation_date_chbox")
        self.dist_point_number_edit = QtWidgets.QLineEdit(self.tab)
        self.dist_point_number_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.dist_point_number_edit.setObjectName("dist_point_number_edit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 126, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 126, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName("label")
        self.inspection_intervall_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(20, 160, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName("inspection_intervall_unit_cbox")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 145, 126, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(270, 15, 126, 16))
        self.label_7.setObjectName("label_7")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(270, 30, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(295, 75, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(270, 80, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(270, 60, 126, 16))
        self.label_8.setObjectName("label_8")
        self.height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(270, 117, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName("height_sbox")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 102, 126, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 147, 126, 16))
        self.label_15.setObjectName("label_15")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 162, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.date_of_last_inspection_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(45, 205, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName("date_of_last_inspection_edit")
        self.date_of_last_inspection_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(20, 210, 26, 17))
        self.date_of_last_inspection_chbox.setText("")
        self.date_of_last_inspection_chbox.setObjectName("date_of_last_inspection_chbox")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 190, 126, 16))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(DistributionPointDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(DistributionPointDialog.accept)
        self.buttonBox.rejected.connect(DistributionPointDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(DistributionPointDialog)
        DistributionPointDialog.setTabOrder(self.tabWidget, self.dist_point_number_edit)
        DistributionPointDialog.setTabOrder(self.dist_point_number_edit, self.installation_date_chbox)
        DistributionPointDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        DistributionPointDialog.setTabOrder(self.installation_date_edit, self.inspection_intervall_sbox)
        DistributionPointDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        DistributionPointDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        DistributionPointDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        DistributionPointDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        DistributionPointDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        DistributionPointDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        DistributionPointDialog.setTabOrder(self.status_change_date_edit, self.height_sbox)
        DistributionPointDialog.setTabOrder(self.height_sbox, self.network_cbox)

    def retranslateUi(self, DistributionPointDialog):
        _translate = QtCore.QCoreApplication.translate
        DistributionPointDialog.setWindowTitle(_translate("DistributionPointDialog", "Add / Edit Distribution Point"))
        self.installation_date_edit.setDisplayFormat(_translate("DistributionPointDialog", "yyyy-MM-dd"))
        self.label_3.setText(_translate("DistributionPointDialog", "Installation Date"))
        self.label_5.setText(_translate("DistributionPointDialog", "Inspection Interval"))
        self.label.setText(_translate("DistributionPointDialog", "Distribution Point Number"))
        self.label_6.setText(_translate("DistributionPointDialog", "Inspection Interval Unit"))
        self.label_7.setText(_translate("DistributionPointDialog", "Operating State"))
        self.status_change_date_edit.setDisplayFormat(_translate("DistributionPointDialog", "yyyy-MM-dd"))
        self.label_8.setText(_translate("DistributionPointDialog", "Date of Status Change"))
        self.label_14.setText(_translate("DistributionPointDialog", "Height [m]"))
        self.label_15.setText(_translate("DistributionPointDialog", "Network"))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("DistributionPointDialog", "yyyy-MM-dd"))
        self.label_13.setText(_translate("DistributionPointDialog", "Date of Last Inspection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DistributionPointDialog", "Description"))

from . import resources_rc
