# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/FittingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FittingDialog(object):
    def setupUi(self, FittingDialog):
        FittingDialog.setObjectName("FittingDialog")
        FittingDialog.resize(588, 480)
        FittingDialog.setMinimumSize(QtCore.QSize(588, 480))
        FittingDialog.setMaximumSize(QtCore.QSize(588, 480))
        self.buttonBox = QtWidgets.QDialogButtonBox(FittingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 440, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(FittingDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 411))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.inspection_intervall_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(20, 170, 196, 22))
        self.inspection_intervall_sbox.setObjectName("inspection_intervall_sbox")
        self.installation_date_edit = QtWidgets.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 120, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName("installation_date_edit")
        self.installation_length_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.installation_length_sbox.setGeometry(QtCore.QRect(20, 75, 196, 22))
        self.installation_length_sbox.setDecimals(1)
        self.installation_length_sbox.setMaximum(500.0)
        self.installation_length_sbox.setObjectName("installation_length_sbox")
        self.installation_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 125, 26, 17))
        self.installation_date_chbox.setText("")
        self.installation_date_chbox.setObjectName("installation_date_chbox")
        self.fitting_no_edit = QtWidgets.QLineEdit(self.tab)
        self.fitting_no_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.fitting_no_edit.setObjectName("fitting_no_edit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 126, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 105, 126, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 155, 126, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName("label")
        self.inspection_intervall_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(20, 215, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName("inspection_intervall_unit_cbox")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 126, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 126, 16))
        self.label_7.setObjectName("label_7")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(20, 305, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(45, 350, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(20, 355, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 335, 126, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 15, 126, 16))
        self.label_9.setObjectName("label_9")
        self.switching_state_cbox = QtWidgets.QComboBox(self.tab)
        self.switching_state_cbox.setGeometry(QtCore.QRect(270, 30, 196, 22))
        self.switching_state_cbox.setObjectName("switching_state_cbox")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(270, 60, 126, 16))
        self.label_10.setObjectName("label_10")
        self.mounting_type_cbox = QtWidgets.QComboBox(self.tab)
        self.mounting_type_cbox.setGeometry(QtCore.QRect(270, 75, 196, 22))
        self.mounting_type_cbox.setObjectName("mounting_type_cbox")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(270, 105, 126, 16))
        self.label_11.setObjectName("label_11")
        self.fitting_type_cbox = QtWidgets.QComboBox(self.tab)
        self.fitting_type_cbox.setGeometry(QtCore.QRect(270, 120, 196, 22))
        self.fitting_type_cbox.setObjectName("fitting_type_cbox")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(270, 150, 126, 16))
        self.label_12.setObjectName("label_12")
        self.fitting_purpose_cbox = QtWidgets.QComboBox(self.tab)
        self.fitting_purpose_cbox.setGeometry(QtCore.QRect(270, 165, 196, 22))
        self.fitting_purpose_cbox.setObjectName("fitting_purpose_cbox")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(270, 195, 126, 16))
        self.label_13.setObjectName("label_13")
        self.nominal_width_cbox = QtWidgets.QComboBox(self.tab)
        self.nominal_width_cbox.setGeometry(QtCore.QRect(270, 210, 196, 22))
        self.nominal_width_cbox.setObjectName("nominal_width_cbox")
        self.height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(270, 255, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName("height_sbox")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 240, 126, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 285, 126, 16))
        self.label_15.setObjectName("label_15")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 300, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.date_of_last_inspection_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(45, 260, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName("date_of_last_inspection_edit")
        self.date_of_last_inspection_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(20, 265, 26, 17))
        self.date_of_last_inspection_chbox.setText("")
        self.date_of_last_inspection_chbox.setObjectName("date_of_last_inspection_chbox")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 245, 126, 16))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(FittingDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(FittingDialog.accept)
        self.buttonBox.rejected.connect(FittingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FittingDialog)
        FittingDialog.setTabOrder(self.tabWidget, self.fitting_no_edit)
        FittingDialog.setTabOrder(self.fitting_no_edit, self.installation_length_sbox)
        FittingDialog.setTabOrder(self.installation_length_sbox, self.installation_date_chbox)
        FittingDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        FittingDialog.setTabOrder(self.installation_date_edit, self.inspection_intervall_sbox)
        FittingDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        FittingDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        FittingDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        FittingDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        FittingDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        FittingDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        FittingDialog.setTabOrder(self.status_change_date_edit, self.switching_state_cbox)
        FittingDialog.setTabOrder(self.switching_state_cbox, self.mounting_type_cbox)
        FittingDialog.setTabOrder(self.mounting_type_cbox, self.fitting_type_cbox)
        FittingDialog.setTabOrder(self.fitting_type_cbox, self.fitting_purpose_cbox)
        FittingDialog.setTabOrder(self.fitting_purpose_cbox, self.nominal_width_cbox)
        FittingDialog.setTabOrder(self.nominal_width_cbox, self.height_sbox)
        FittingDialog.setTabOrder(self.height_sbox, self.network_cbox)
        FittingDialog.setTabOrder(self.network_cbox, self.buttonBox)

    def retranslateUi(self, FittingDialog):
        _translate = QtCore.QCoreApplication.translate
        FittingDialog.setWindowTitle(_translate("FittingDialog", "Add / Edit Fitting"))
        self.installation_date_edit.setDisplayFormat(_translate("FittingDialog", "yyyy-MM-dd"))
        self.label_2.setText(_translate("FittingDialog", "Installation Length [cm]"))
        self.label_3.setText(_translate("FittingDialog", "Installation Date"))
        self.label_5.setText(_translate("FittingDialog", "Inspection Intervall"))
        self.label.setText(_translate("FittingDialog", "Fitting Number"))
        self.label_6.setText(_translate("FittingDialog", "Inspection Intervall Unit"))
        self.label_7.setText(_translate("FittingDialog", "Operating State"))
        self.status_change_date_edit.setDisplayFormat(_translate("FittingDialog", "yyyy-MM-dd"))
        self.label_8.setText(_translate("FittingDialog", "Date of Status Change"))
        self.label_9.setText(_translate("FittingDialog", "Switching State"))
        self.label_10.setText(_translate("FittingDialog", "Mounting Type"))
        self.label_11.setText(_translate("FittingDialog", "Fitting Type"))
        self.label_12.setText(_translate("FittingDialog", "Fitting Purpose"))
        self.label_13.setText(_translate("FittingDialog", "Nominal Width"))
        self.label_14.setText(_translate("FittingDialog", "Height [m]"))
        self.label_15.setText(_translate("FittingDialog", "Network"))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("FittingDialog", "yyyy-MM-dd"))
        self.label_16.setText(_translate("FittingDialog", "Date of Last Inspection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FittingDialog", "Description"))

from . import resources_rc
