# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/FlatrateConnectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FlatrateConnectionDialog(object):
    def setupUi(self, FlatrateConnectionDialog):
        FlatrateConnectionDialog.setObjectName("FlatrateConnectionDialog")
        FlatrateConnectionDialog.resize(588, 532)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FlatrateConnectionDialog.sizePolicy().hasHeightForWidth())
        FlatrateConnectionDialog.setSizePolicy(sizePolicy)
        FlatrateConnectionDialog.setMinimumSize(QtCore.QSize(588, 450))
        FlatrateConnectionDialog.setMaximumSize(QtCore.QSize(588, 640))
        self.buttonBox = QtWidgets.QDialogButtonBox(FlatrateConnectionDialog)
        self.buttonBox.setGeometry(QtCore.QRect(390, 490, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(FlatrateConnectionDialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 561, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.inspection_intervall_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(265, 70, 196, 22))
        self.inspection_intervall_sbox.setObjectName("inspection_intervall_sbox")
        self.installation_date_edit = QtWidgets.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 350, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName("installation_date_edit")
        self.installation_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 355, 26, 17))
        self.installation_date_chbox.setText("")
        self.installation_date_chbox.setObjectName("installation_date_chbox")
        self.connection_no_edit = QtWidgets.QLineEdit(self.tab)
        self.connection_no_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.connection_no_edit.setObjectName("connection_no_edit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 335, 126, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(265, 55, 126, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 141, 16))
        self.label.setObjectName("label")
        self.inspection_intervall_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(265, 110, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName("inspection_intervall_unit_cbox")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(265, 95, 126, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(265, 175, 126, 16))
        self.label_7.setObjectName("label_7")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(265, 190, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(265, 270, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName("height_sbox")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(265, 255, 126, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(265, 295, 126, 16))
        self.label_15.setObjectName("label_15")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(265, 310, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.date_of_last_inspection_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(290, 150, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName("date_of_last_inspection_edit")
        self.date_of_last_inspection_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(265, 155, 26, 17))
        self.date_of_last_inspection_chbox.setText("")
        self.date_of_last_inspection_chbox.setObjectName("date_of_last_inspection_chbox")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(265, 135, 126, 16))
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 55, 211, 16))
        self.label_2.setObjectName("label_2")
        self.plot_no_edit = QtWidgets.QLineEdit(self.tab)
        self.plot_no_edit.setGeometry(QtCore.QRect(20, 150, 196, 20))
        self.plot_no_edit.setObjectName("plot_no_edit")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 135, 141, 16))
        self.label_16.setObjectName("label_16")
        self.district_edit = QtWidgets.QLineEdit(self.tab)
        self.district_edit.setGeometry(QtCore.QRect(20, 190, 196, 20))
        self.district_edit.setObjectName("district_edit")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(20, 175, 141, 16))
        self.label_17.setObjectName("label_17")
        self.zone_edit = QtWidgets.QLineEdit(self.tab)
        self.zone_edit.setGeometry(QtCore.QRect(20, 230, 196, 20))
        self.zone_edit.setObjectName("zone_edit")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 215, 141, 16))
        self.label_18.setObjectName("label_18")
        self.ward_edit = QtWidgets.QLineEdit(self.tab)
        self.ward_edit.setGeometry(QtCore.QRect(20, 270, 196, 20))
        self.ward_edit.setText("")
        self.ward_edit.setObjectName("ward_edit")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(20, 255, 141, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(20, 295, 141, 16))
        self.label_20.setObjectName("label_20")
        self.street_edit = QtWidgets.QLineEdit(self.tab)
        self.street_edit.setGeometry(QtCore.QRect(20, 310, 196, 20))
        self.street_edit.setText("")
        self.street_edit.setObjectName("street_edit")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(265, 15, 126, 16))
        self.label_22.setObjectName("label_22")
        self.date_of_first_use_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_first_use_edit.setEnabled(False)
        self.date_of_first_use_edit.setGeometry(QtCore.QRect(290, 30, 171, 22))
        self.date_of_first_use_edit.setCalendarPopup(True)
        self.date_of_first_use_edit.setObjectName("date_of_first_use_edit")
        self.date_of_first_use_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_first_use_chbox.setGeometry(QtCore.QRect(265, 35, 26, 17))
        self.date_of_first_use_chbox.setText("")
        self.date_of_first_use_chbox.setObjectName("date_of_first_use_chbox")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(265, 235, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(265, 215, 126, 16))
        self.label_21.setObjectName("label_21")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(290, 230, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.view_maxcom_button = QtWidgets.QPushButton(self.tab)
        self.view_maxcom_button.setGeometry(QtCore.QRect(190, 95, 25, 25))
        self.view_maxcom_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/wnt/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_maxcom_button.setIcon(icon)
        self.view_maxcom_button.setObjectName("view_maxcom_button")
        self.verify_button = QtWidgets.QPushButton(self.tab)
        self.verify_button.setGeometry(QtCore.QRect(160, 95, 25, 25))
        self.verify_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/wnt/verify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verify_button.setIcon(icon1)
        self.verify_button.setObjectName("verify_button")
        self.control_no_sbox = QtWidgets.QSpinBox(self.tab)
        self.control_no_sbox.setGeometry(QtCore.QRect(20, 70, 196, 22))
        self.control_no_sbox.setMinimum(-1)
        self.control_no_sbox.setMaximum(8000000)
        self.control_no_sbox.setProperty("value", -1)
        self.control_no_sbox.setObjectName("control_no_sbox")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(FlatrateConnectionDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(FlatrateConnectionDialog.accept)
        self.buttonBox.rejected.connect(FlatrateConnectionDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(FlatrateConnectionDialog)
        FlatrateConnectionDialog.setTabOrder(self.tabWidget, self.connection_no_edit)
        FlatrateConnectionDialog.setTabOrder(self.connection_no_edit, self.control_no_sbox)
        FlatrateConnectionDialog.setTabOrder(self.control_no_sbox, self.verify_button)
        FlatrateConnectionDialog.setTabOrder(self.verify_button, self.view_maxcom_button)
        FlatrateConnectionDialog.setTabOrder(self.view_maxcom_button, self.plot_no_edit)
        FlatrateConnectionDialog.setTabOrder(self.plot_no_edit, self.district_edit)
        FlatrateConnectionDialog.setTabOrder(self.district_edit, self.zone_edit)
        FlatrateConnectionDialog.setTabOrder(self.zone_edit, self.ward_edit)
        FlatrateConnectionDialog.setTabOrder(self.ward_edit, self.street_edit)
        FlatrateConnectionDialog.setTabOrder(self.street_edit, self.installation_date_chbox)
        FlatrateConnectionDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        FlatrateConnectionDialog.setTabOrder(self.installation_date_edit, self.date_of_first_use_chbox)
        FlatrateConnectionDialog.setTabOrder(self.date_of_first_use_chbox, self.date_of_first_use_edit)
        FlatrateConnectionDialog.setTabOrder(self.date_of_first_use_edit, self.inspection_intervall_sbox)
        FlatrateConnectionDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        FlatrateConnectionDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        FlatrateConnectionDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        FlatrateConnectionDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        FlatrateConnectionDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        FlatrateConnectionDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        FlatrateConnectionDialog.setTabOrder(self.status_change_date_edit, self.height_sbox)
        FlatrateConnectionDialog.setTabOrder(self.height_sbox, self.network_cbox)
        FlatrateConnectionDialog.setTabOrder(self.network_cbox, self.buttonBox)

    def retranslateUi(self, FlatrateConnectionDialog):
        _translate = QtCore.QCoreApplication.translate
        FlatrateConnectionDialog.setWindowTitle(_translate("FlatrateConnectionDialog", "Add / Edit Flatrate Connection"))
        self.installation_date_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd"))
        self.label_3.setText(_translate("FlatrateConnectionDialog", "Installation Date"))
        self.label_5.setText(_translate("FlatrateConnectionDialog", "Inspection Interval"))
        self.label.setText(_translate("FlatrateConnectionDialog", "Flatrate Connection Number"))
        self.label_6.setText(_translate("FlatrateConnectionDialog", "Inspection Interval Unit"))
        self.label_7.setText(_translate("FlatrateConnectionDialog", "Operating State"))
        self.label_14.setText(_translate("FlatrateConnectionDialog", "Height [m]"))
        self.label_15.setText(_translate("FlatrateConnectionDialog", "Network"))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd"))
        self.label_13.setText(_translate("FlatrateConnectionDialog", "Date of Last Inspection"))
        self.label_2.setText(_translate("FlatrateConnectionDialog", "Application Control No. (from MAXCOM)"))
        self.label_16.setText(_translate("FlatrateConnectionDialog", "Plot Number"))
        self.label_17.setText(_translate("FlatrateConnectionDialog", "District"))
        self.label_18.setText(_translate("FlatrateConnectionDialog", "Zone"))
        self.label_19.setText(_translate("FlatrateConnectionDialog", "Ward"))
        self.label_20.setText(_translate("FlatrateConnectionDialog", "Street"))
        self.label_22.setText(_translate("FlatrateConnectionDialog", "Date of First Use"))
        self.date_of_first_use_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd"))
        self.label_21.setText(_translate("FlatrateConnectionDialog", "Date of Status Change"))
        self.status_change_date_edit.setDisplayFormat(_translate("FlatrateConnectionDialog", "yyyy-MM-dd"))
        self.view_maxcom_button.setToolTip(_translate("FlatrateConnectionDialog", "View Application Details at MAXCOM"))
        self.verify_button.setToolTip(_translate("FlatrateConnectionDialog", "Verify Control Number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("FlatrateConnectionDialog", "Description"))

from . import resources_rc
