# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/IntakeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IntakeDialog(object):
    def setupUi(self, IntakeDialog):
        IntakeDialog.setObjectName("IntakeDialog")
        IntakeDialog.resize(588, 410)
        IntakeDialog.setMinimumSize(QtCore.QSize(588, 410))
        IntakeDialog.setMaximumSize(QtCore.QSize(588, 480))
        self.buttonBox = QtWidgets.QDialogButtonBox(IntakeDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 360, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(IntakeDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 331))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.intake_no_edit = QtWidgets.QLineEdit(self.tab)
        self.intake_no_edit.setGeometry(QtCore.QRect(20, 40, 196, 20))
        self.intake_no_edit.setObjectName("intake_no_edit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(280, 25, 126, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 25, 126, 16))
        self.label.setObjectName("label")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(305, 130, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(280, 135, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(280, 115, 126, 16))
        self.label_8.setObjectName("label_8")
        self.height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(280, 175, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName("height_sbox")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(280, 160, 126, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(280, 205, 126, 16))
        self.label_15.setObjectName("label_15")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(280, 220, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.installation_year_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.installation_year_sbox.setGeometry(QtCore.QRect(280, 40, 196, 22))
        self.installation_year_sbox.setDecimals(0)
        self.installation_year_sbox.setMaximum(3000.0)
        self.installation_year_sbox.setProperty("value", 0.0)
        self.installation_year_sbox.setObjectName("installation_year_sbox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 126, 16))
        self.label_2.setObjectName("label_2")
        self.intake_source_cbox = QtWidgets.QComboBox(self.tab)
        self.intake_source_cbox.setGeometry(QtCore.QRect(20, 85, 196, 22))
        self.intake_source_cbox.setObjectName("intake_source_cbox")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 115, 126, 16))
        self.label_5.setObjectName("label_5")
        self.intake_type_cbox = QtWidgets.QComboBox(self.tab)
        self.intake_type_cbox.setGeometry(QtCore.QRect(20, 130, 196, 22))
        self.intake_type_cbox.setObjectName("intake_type_cbox")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 205, 126, 16))
        self.label_16.setObjectName("label_16")
        self.capacity_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.capacity_sbox.setGeometry(QtCore.QRect(20, 220, 196, 22))
        self.capacity_sbox.setMinimum(0.0)
        self.capacity_sbox.setMaximum(200000.0)
        self.capacity_sbox.setObjectName("capacity_sbox")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(280, 85, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(280, 70, 126, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 126, 16))
        self.label_10.setObjectName("label_10")
        self.capacity_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.capacity_unit_cbox.setGeometry(QtCore.QRect(20, 175, 196, 22))
        self.capacity_unit_cbox.setObjectName("capacity_unit_cbox")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(IntakeDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(IntakeDialog.accept)
        self.buttonBox.rejected.connect(IntakeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(IntakeDialog)
        IntakeDialog.setTabOrder(self.tabWidget, self.intake_no_edit)
        IntakeDialog.setTabOrder(self.intake_no_edit, self.intake_source_cbox)
        IntakeDialog.setTabOrder(self.intake_source_cbox, self.intake_type_cbox)
        IntakeDialog.setTabOrder(self.intake_type_cbox, self.capacity_unit_cbox)
        IntakeDialog.setTabOrder(self.capacity_unit_cbox, self.capacity_sbox)
        IntakeDialog.setTabOrder(self.capacity_sbox, self.installation_year_sbox)
        IntakeDialog.setTabOrder(self.installation_year_sbox, self.operating_state_cbox)
        IntakeDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        IntakeDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        IntakeDialog.setTabOrder(self.status_change_date_edit, self.height_sbox)
        IntakeDialog.setTabOrder(self.height_sbox, self.network_cbox)

    def retranslateUi(self, IntakeDialog):
        _translate = QtCore.QCoreApplication.translate
        IntakeDialog.setWindowTitle(_translate("IntakeDialog", "Add / Edit Intake"))
        self.label_3.setText(_translate("IntakeDialog", "Installation Year"))
        self.label.setText(_translate("IntakeDialog", "Intake Number"))
        self.status_change_date_edit.setDisplayFormat(_translate("IntakeDialog", "yyyy-MM-dd"))
        self.label_8.setText(_translate("IntakeDialog", "Date of Status Change"))
        self.label_14.setText(_translate("IntakeDialog", "Height [m]"))
        self.label_15.setText(_translate("IntakeDialog", "Network"))
        self.label_2.setText(_translate("IntakeDialog", "Intake Source"))
        self.label_5.setText(_translate("IntakeDialog", "Intake Type"))
        self.label_16.setText(_translate("IntakeDialog", "Capacity"))
        self.label_9.setText(_translate("IntakeDialog", "Operating State"))
        self.label_10.setText(_translate("IntakeDialog", "Capacity Unit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("IntakeDialog", "Description"))

from . import resources_rc
