# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/LineCasingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LineCasingDialog(object):
    def setupUi(self, LineCasingDialog):
        LineCasingDialog.setObjectName("LineCasingDialog")
        LineCasingDialog.resize(588, 390)
        LineCasingDialog.setMinimumSize(QtCore.QSize(588, 390))
        LineCasingDialog.setMaximumSize(QtCore.QSize(588, 480))
        self.buttonBox = QtWidgets.QDialogButtonBox(LineCasingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 340, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(LineCasingDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 321))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.inspection_intervall_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(20, 110, 196, 22))
        self.inspection_intervall_sbox.setObjectName("inspection_intervall_sbox")
        self.installation_date_edit = QtWidgets.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 70, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName("installation_date_edit")
        self.installation_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 75, 26, 17))
        self.installation_date_chbox.setText("")
        self.installation_date_chbox.setObjectName("installation_date_chbox")
        self.line_casing_number_edit = QtWidgets.QLineEdit(self.tab)
        self.line_casing_number_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.line_casing_number_edit.setObjectName("line_casing_number_edit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 55, 126, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 95, 126, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName("label")
        self.inspection_intervall_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(20, 155, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName("inspection_intervall_unit_cbox")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 126, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 15, 126, 16))
        self.label_9.setObjectName("label_9")
        self.casing_type_cbox = QtWidgets.QComboBox(self.tab)
        self.casing_type_cbox.setGeometry(QtCore.QRect(270, 30, 196, 22))
        self.casing_type_cbox.setObjectName("casing_type_cbox")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 226, 126, 16))
        self.label_15.setObjectName("label_15")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 241, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.date_of_last_inspection_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(45, 200, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName("date_of_last_inspection_edit")
        self.date_of_last_inspection_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(20, 205, 26, 17))
        self.date_of_last_inspection_chbox.setText("")
        self.date_of_last_inspection_chbox.setObjectName("date_of_last_inspection_chbox")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 185, 126, 16))
        self.label_13.setObjectName("label_13")
        self.length_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.length_sbox.setGeometry(QtCore.QRect(270, 71, 196, 22))
        self.length_sbox.setDecimals(1)
        self.length_sbox.setMaximum(500.0)
        self.length_sbox.setObjectName("length_sbox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(270, 56, 126, 16))
        self.label_2.setObjectName("label_2")
        self.outer_height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.outer_height_sbox.setGeometry(QtCore.QRect(270, 111, 196, 22))
        self.outer_height_sbox.setDecimals(1)
        self.outer_height_sbox.setMaximum(500.0)
        self.outer_height_sbox.setObjectName("outer_height_sbox")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(270, 96, 126, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(270, 141, 126, 16))
        self.label_8.setObjectName("label_8")
        self.outer_width_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.outer_width_sbox.setGeometry(QtCore.QRect(270, 156, 196, 22))
        self.outer_width_sbox.setDecimals(1)
        self.outer_width_sbox.setMaximum(500.0)
        self.outer_width_sbox.setObjectName("outer_width_sbox")
        self.jacket_pipe_diameter_cbox = QtWidgets.QComboBox(self.tab)
        self.jacket_pipe_diameter_cbox.setGeometry(QtCore.QRect(270, 201, 196, 22))
        self.jacket_pipe_diameter_cbox.setObjectName("jacket_pipe_diameter_cbox")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(270, 186, 126, 16))
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(LineCasingDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(LineCasingDialog.accept)
        self.buttonBox.rejected.connect(LineCasingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LineCasingDialog)
        LineCasingDialog.setTabOrder(self.tabWidget, self.line_casing_number_edit)
        LineCasingDialog.setTabOrder(self.line_casing_number_edit, self.installation_date_chbox)
        LineCasingDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        LineCasingDialog.setTabOrder(self.installation_date_edit, self.inspection_intervall_sbox)
        LineCasingDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        LineCasingDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        LineCasingDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        LineCasingDialog.setTabOrder(self.date_of_last_inspection_edit, self.casing_type_cbox)
        LineCasingDialog.setTabOrder(self.casing_type_cbox, self.length_sbox)
        LineCasingDialog.setTabOrder(self.length_sbox, self.outer_height_sbox)
        LineCasingDialog.setTabOrder(self.outer_height_sbox, self.outer_width_sbox)
        LineCasingDialog.setTabOrder(self.outer_width_sbox, self.jacket_pipe_diameter_cbox)
        LineCasingDialog.setTabOrder(self.jacket_pipe_diameter_cbox, self.network_cbox)

    def retranslateUi(self, LineCasingDialog):
        _translate = QtCore.QCoreApplication.translate
        LineCasingDialog.setWindowTitle(_translate("LineCasingDialog", "Add / Edit Line Casing"))
        self.installation_date_edit.setDisplayFormat(_translate("LineCasingDialog", "yyyy-MM-dd"))
        self.label_3.setText(_translate("LineCasingDialog", "Installation Date"))
        self.label_5.setText(_translate("LineCasingDialog", "Inspection Interval"))
        self.label.setText(_translate("LineCasingDialog", "Line Casing Number"))
        self.label_6.setText(_translate("LineCasingDialog", "Inspection Interval Unit"))
        self.label_9.setText(_translate("LineCasingDialog", "Casing Type"))
        self.label_15.setText(_translate("LineCasingDialog", "Network"))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("LineCasingDialog", "yyyy-MM-dd"))
        self.label_13.setText(_translate("LineCasingDialog", "Date of Last Inspection"))
        self.label_2.setText(_translate("LineCasingDialog", "Length [m]"))
        self.label_7.setText(_translate("LineCasingDialog", "Outer Height [m]"))
        self.label_8.setText(_translate("LineCasingDialog", "Outer Width [mm]"))
        self.label_16.setText(_translate("LineCasingDialog", "Jacket Pipe Diameter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LineCasingDialog", "Description"))

from . import resources_rc
