# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/MeterDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MeterDialog(object):
    def setupUi(self, MeterDialog):
        MeterDialog.setObjectName("MeterDialog")
        MeterDialog.resize(588, 575)
        MeterDialog.setMinimumSize(QtCore.QSize(588, 450))
        MeterDialog.setMaximumSize(QtCore.QSize(588, 640))
        self.buttonBox = QtWidgets.QDialogButtonBox(MeterDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 540, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(MeterDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.meter_number_edit = QtWidgets.QLineEdit(self.tab)
        self.meter_number_edit.setGeometry(QtCore.QRect(27, 30, 196, 20))
        self.meter_number_edit.setObjectName("meter_number_edit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(27, 15, 126, 16))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(265, 135, 126, 16))
        self.label_7.setObjectName("label_7")
        self.inspection_intervall_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.inspection_intervall_unit_cbox.setGeometry(QtCore.QRect(265, 70, 196, 22))
        self.inspection_intervall_unit_cbox.setObjectName("inspection_intervall_unit_cbox")
        self.plot_no_edit = QtWidgets.QLineEdit(self.tab)
        self.plot_no_edit.setGeometry(QtCore.QRect(25, 150, 196, 20))
        self.plot_no_edit.setObjectName("plot_no_edit")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(265, 335, 126, 16))
        self.label_15.setObjectName("label_15")
        self.district_edit = QtWidgets.QLineEdit(self.tab)
        self.district_edit.setGeometry(QtCore.QRect(25, 190, 196, 20))
        self.district_edit.setObjectName("district_edit")
        self.street_edit = QtWidgets.QLineEdit(self.tab)
        self.street_edit.setGeometry(QtCore.QRect(25, 310, 196, 20))
        self.street_edit.setText("")
        self.street_edit.setObjectName("street_edit")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(265, 175, 126, 16))
        self.label_21.setObjectName("label_21")
        self.ward_edit = QtWidgets.QLineEdit(self.tab)
        self.ward_edit.setGeometry(QtCore.QRect(25, 270, 196, 20))
        self.ward_edit.setText("")
        self.ward_edit.setObjectName("ward_edit")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(265, 295, 126, 16))
        self.label_14.setObjectName("label_14")
        self.installation_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(25, 355, 26, 17))
        self.installation_date_chbox.setText("")
        self.installation_date_chbox.setObjectName("installation_date_chbox")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(25, 335, 126, 16))
        self.label_3.setObjectName("label_3")
        self.date_of_first_use_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_first_use_chbox.setGeometry(QtCore.QRect(25, 405, 26, 17))
        self.date_of_first_use_chbox.setText("")
        self.date_of_first_use_chbox.setObjectName("date_of_first_use_chbox")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(265, 350, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(25, 385, 126, 16))
        self.label_22.setObjectName("label_22")
        self.date_of_last_inspection_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(265, 115, 26, 17))
        self.date_of_last_inspection_chbox.setText("")
        self.date_of_last_inspection_chbox.setObjectName("date_of_last_inspection_chbox")
        self.inspection_intervall_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.inspection_intervall_sbox.setGeometry(QtCore.QRect(265, 30, 196, 22))
        self.inspection_intervall_sbox.setObjectName("inspection_intervall_sbox")
        self.date_of_last_inspection_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(290, 110, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName("date_of_last_inspection_edit")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(265, 95, 126, 16))
        self.label_13.setObjectName("label_13")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(290, 190, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(25, 255, 141, 16))
        self.label_19.setObjectName("label_19")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(265, 150, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(25, 55, 216, 16))
        self.label_2.setObjectName("label_2")
        self.installation_date_edit = QtWidgets.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(50, 350, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName("installation_date_edit")
        self.height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(265, 310, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName("height_sbox")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(25, 295, 141, 16))
        self.label_20.setObjectName("label_20")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(25, 135, 141, 16))
        self.label_16.setObjectName("label_16")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(265, 15, 126, 16))
        self.label_5.setObjectName("label_5")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(25, 175, 141, 16))
        self.label_17.setObjectName("label_17")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(265, 195, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.date_of_first_use_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_first_use_edit.setEnabled(False)
        self.date_of_first_use_edit.setGeometry(QtCore.QRect(50, 400, 171, 22))
        self.date_of_first_use_edit.setCalendarPopup(True)
        self.date_of_first_use_edit.setObjectName("date_of_first_use_edit")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(25, 215, 141, 16))
        self.label_18.setObjectName("label_18")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(265, 55, 126, 16))
        self.label_6.setObjectName("label_6")
        self.meter_class_cbox = QtWidgets.QComboBox(self.tab)
        self.meter_class_cbox.setGeometry(QtCore.QRect(265, 230, 196, 22))
        self.meter_class_cbox.setObjectName("meter_class_cbox")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(265, 215, 126, 16))
        self.label_9.setObjectName("label_9")
        self.meter_type_cbox = QtWidgets.QComboBox(self.tab)
        self.meter_type_cbox.setGeometry(QtCore.QRect(265, 270, 196, 22))
        self.meter_type_cbox.setObjectName("meter_type_cbox")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(265, 255, 126, 16))
        self.label_10.setObjectName("label_10")
        self.zone_edit = QtWidgets.QLineEdit(self.tab)
        self.zone_edit.setGeometry(QtCore.QRect(25, 230, 196, 20))
        self.zone_edit.setObjectName("zone_edit")
        self.view_maxcom_button = QtWidgets.QPushButton(self.tab)
        self.view_maxcom_button.setGeometry(QtCore.QRect(195, 100, 25, 25))
        self.view_maxcom_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/wnt/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_maxcom_button.setIcon(icon)
        self.view_maxcom_button.setObjectName("view_maxcom_button")
        self.verify_button = QtWidgets.QPushButton(self.tab)
        self.verify_button.setGeometry(QtCore.QRect(160, 100, 25, 25))
        self.verify_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/wnt/verify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verify_button.setIcon(icon1)
        self.verify_button.setObjectName("verify_button")
        self.control_no_sbox = QtWidgets.QSpinBox(self.tab)
        self.control_no_sbox.setGeometry(QtCore.QRect(25, 70, 196, 22))
        self.control_no_sbox.setMinimum(-1)
        self.control_no_sbox.setMaximum(8000000)
        self.control_no_sbox.setProperty("value", -1)
        self.control_no_sbox.setObjectName("control_no_sbox")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(MeterDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(MeterDialog.accept)
        self.buttonBox.rejected.connect(MeterDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MeterDialog)
        MeterDialog.setTabOrder(self.tabWidget, self.meter_number_edit)
        MeterDialog.setTabOrder(self.meter_number_edit, self.control_no_sbox)
        MeterDialog.setTabOrder(self.control_no_sbox, self.verify_button)
        MeterDialog.setTabOrder(self.verify_button, self.view_maxcom_button)
        MeterDialog.setTabOrder(self.view_maxcom_button, self.plot_no_edit)
        MeterDialog.setTabOrder(self.plot_no_edit, self.district_edit)
        MeterDialog.setTabOrder(self.district_edit, self.zone_edit)
        MeterDialog.setTabOrder(self.zone_edit, self.ward_edit)
        MeterDialog.setTabOrder(self.ward_edit, self.street_edit)
        MeterDialog.setTabOrder(self.street_edit, self.installation_date_chbox)
        MeterDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        MeterDialog.setTabOrder(self.installation_date_edit, self.date_of_first_use_chbox)
        MeterDialog.setTabOrder(self.date_of_first_use_chbox, self.date_of_first_use_edit)
        MeterDialog.setTabOrder(self.date_of_first_use_edit, self.inspection_intervall_sbox)
        MeterDialog.setTabOrder(self.inspection_intervall_sbox, self.inspection_intervall_unit_cbox)
        MeterDialog.setTabOrder(self.inspection_intervall_unit_cbox, self.date_of_last_inspection_chbox)
        MeterDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        MeterDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        MeterDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        MeterDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        MeterDialog.setTabOrder(self.status_change_date_edit, self.meter_class_cbox)
        MeterDialog.setTabOrder(self.meter_class_cbox, self.meter_type_cbox)
        MeterDialog.setTabOrder(self.meter_type_cbox, self.height_sbox)
        MeterDialog.setTabOrder(self.height_sbox, self.network_cbox)
        MeterDialog.setTabOrder(self.network_cbox, self.buttonBox)

    def retranslateUi(self, MeterDialog):
        _translate = QtCore.QCoreApplication.translate
        MeterDialog.setWindowTitle(_translate("MeterDialog", "Add / Edit Meter"))
        self.label.setText(_translate("MeterDialog", "Meter Number"))
        self.label_7.setText(_translate("MeterDialog", "Operating State"))
        self.label_15.setText(_translate("MeterDialog", "Network"))
        self.label_21.setText(_translate("MeterDialog", "Date of Status Change"))
        self.label_14.setText(_translate("MeterDialog", "Height [m]"))
        self.label_3.setText(_translate("MeterDialog", "Installation Date"))
        self.label_22.setText(_translate("MeterDialog", "Date of First Use"))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("MeterDialog", "yyyy-MM-dd"))
        self.label_13.setText(_translate("MeterDialog", "Date of Last Inspection"))
        self.status_change_date_edit.setDisplayFormat(_translate("MeterDialog", "yyyy-MM-dd"))
        self.label_19.setText(_translate("MeterDialog", "Ward"))
        self.label_2.setText(_translate("MeterDialog", "Application Control No. (from MAXCOM)"))
        self.installation_date_edit.setDisplayFormat(_translate("MeterDialog", "yyyy-MM-dd"))
        self.label_20.setText(_translate("MeterDialog", "Street"))
        self.label_16.setText(_translate("MeterDialog", "Plot Number"))
        self.label_5.setText(_translate("MeterDialog", "Inspection Interval"))
        self.label_17.setText(_translate("MeterDialog", "District"))
        self.date_of_first_use_edit.setDisplayFormat(_translate("MeterDialog", "yyyy-MM-dd"))
        self.label_18.setText(_translate("MeterDialog", "Zone"))
        self.label_6.setText(_translate("MeterDialog", "Inspection Interval Unit"))
        self.label_9.setText(_translate("MeterDialog", "Meter Class"))
        self.label_10.setText(_translate("MeterDialog", "Meter Type"))
        self.view_maxcom_button.setToolTip(_translate("MeterDialog", "View Application Details at MAXCOM"))
        self.verify_button.setToolTip(_translate("MeterDialog", "Verify Control Number"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MeterDialog", "Description"))

from . import resources_rc
