# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/PipelineSegmentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PipelineSegmentDialog(object):
    def setupUi(self, PipelineSegmentDialog):
        PipelineSegmentDialog.setObjectName("PipelineSegmentDialog")
        PipelineSegmentDialog.resize(588, 610)
        PipelineSegmentDialog.setMinimumSize(QtCore.QSize(588, 480))
        PipelineSegmentDialog.setMaximumSize(QtCore.QSize(588, 610))
        self.buttonBox = QtWidgets.QDialogButtonBox(PipelineSegmentDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 570, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(PipelineSegmentDialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 556, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.inspection_interval_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.inspection_interval_sbox.setGeometry(QtCore.QRect(20, 170, 196, 22))
        self.inspection_interval_sbox.setObjectName("inspection_interval_sbox")
        self.installation_date_edit = QtWidgets.QDateEdit(self.tab)
        self.installation_date_edit.setEnabled(False)
        self.installation_date_edit.setGeometry(QtCore.QRect(45, 120, 171, 22))
        self.installation_date_edit.setCalendarPopup(True)
        self.installation_date_edit.setObjectName("installation_date_edit")
        self.installation_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.installation_date_chbox.setGeometry(QtCore.QRect(20, 125, 26, 17))
        self.installation_date_chbox.setText("")
        self.installation_date_chbox.setObjectName("installation_date_chbox")
        self.segment_no_edit = QtWidgets.QLineEdit(self.tab)
        self.segment_no_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.segment_no_edit.setObjectName("segment_no_edit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 126, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 105, 126, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 155, 126, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName("label")
        self.inspection_interval_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.inspection_interval_unit_cbox.setGeometry(QtCore.QRect(20, 215, 196, 22))
        self.inspection_interval_unit_cbox.setObjectName("inspection_interval_unit_cbox")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 126, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 290, 126, 16))
        self.label_7.setObjectName("label_7")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(20, 305, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(45, 350, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(20, 355, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(20, 335, 126, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 15, 126, 16))
        self.label_9.setObjectName("label_9")
        self.pipeline_type_cbox = QtWidgets.QComboBox(self.tab)
        self.pipeline_type_cbox.setGeometry(QtCore.QRect(270, 30, 196, 22))
        self.pipeline_type_cbox.setObjectName("pipeline_type_cbox")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(270, 60, 126, 16))
        self.label_10.setObjectName("label_10")
        self.mounting_type_cbox = QtWidgets.QComboBox(self.tab)
        self.mounting_type_cbox.setGeometry(QtCore.QRect(270, 75, 196, 22))
        self.mounting_type_cbox.setObjectName("mounting_type_cbox")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(270, 105, 126, 16))
        self.label_11.setObjectName("label_11")
        self.material_cbox = QtWidgets.QComboBox(self.tab)
        self.material_cbox.setGeometry(QtCore.QRect(270, 120, 196, 22))
        self.material_cbox.setObjectName("material_cbox")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(270, 155, 126, 16))
        self.label_12.setObjectName("label_12")
        self.placement_type_cbox = QtWidgets.QComboBox(self.tab)
        self.placement_type_cbox.setGeometry(QtCore.QRect(270, 170, 196, 22))
        self.placement_type_cbox.setObjectName("placement_type_cbox")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(270, 200, 126, 16))
        self.label_13.setObjectName("label_13")
        self.nominal_width_cbox = QtWidgets.QComboBox(self.tab)
        self.nominal_width_cbox.setGeometry(QtCore.QRect(270, 215, 196, 22))
        self.nominal_width_cbox.setObjectName("nominal_width_cbox")
        self.outside_diameter_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.outside_diameter_sbox.setGeometry(QtCore.QRect(270, 305, 196, 22))
        self.outside_diameter_sbox.setMinimum(-100.0)
        self.outside_diameter_sbox.setMaximum(2000.0)
        self.outside_diameter_sbox.setObjectName("outside_diameter_sbox")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 290, 126, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(20, 380, 126, 16))
        self.label_15.setObjectName("label_15")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(20, 395, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.positional_accuracy_cbox = QtWidgets.QComboBox(self.tab)
        self.positional_accuracy_cbox.setGeometry(QtCore.QRect(270, 265, 196, 22))
        self.positional_accuracy_cbox.setObjectName("positional_accuracy_cbox")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(270, 250, 126, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(270, 335, 126, 16))
        self.label_18.setObjectName("label_18")
        self.wall_thickness_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.wall_thickness_sbox.setGeometry(QtCore.QRect(270, 350, 196, 22))
        self.wall_thickness_sbox.setMinimum(-100.0)
        self.wall_thickness_sbox.setMaximum(2000.0)
        self.wall_thickness_sbox.setObjectName("wall_thickness_sbox")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(270, 380, 126, 16))
        self.label_19.setObjectName("label_19")
        self.height_at_start_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_at_start_sbox.setGeometry(QtCore.QRect(270, 395, 196, 22))
        self.height_at_start_sbox.setMinimum(-100.0)
        self.height_at_start_sbox.setMaximum(2000.0)
        self.height_at_start_sbox.setObjectName("height_at_start_sbox")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(270, 425, 126, 16))
        self.label_20.setObjectName("label_20")
        self.height_at_end_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_at_end_sbox.setGeometry(QtCore.QRect(270, 440, 196, 22))
        self.height_at_end_sbox.setMinimum(-100.0)
        self.height_at_end_sbox.setMaximum(2000.0)
        self.height_at_end_sbox.setObjectName("height_at_end_sbox")
        self.date_of_last_inspection_chbox = QtWidgets.QCheckBox(self.tab)
        self.date_of_last_inspection_chbox.setGeometry(QtCore.QRect(20, 270, 26, 17))
        self.date_of_last_inspection_chbox.setText("")
        self.date_of_last_inspection_chbox.setObjectName("date_of_last_inspection_chbox")
        self.date_of_last_inspection_edit = QtWidgets.QDateEdit(self.tab)
        self.date_of_last_inspection_edit.setEnabled(False)
        self.date_of_last_inspection_edit.setGeometry(QtCore.QRect(45, 265, 171, 22))
        self.date_of_last_inspection_edit.setCalendarPopup(True)
        self.date_of_last_inspection_edit.setObjectName("date_of_last_inspection_edit")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(20, 250, 126, 16))
        self.label_21.setObjectName("label_21")
        self.length_edit = QtWidgets.QLineEdit(self.tab)
        self.length_edit.setGeometry(QtCore.QRect(20, 75, 196, 20))
        self.length_edit.setReadOnly(True)
        self.length_edit.setObjectName("length_edit")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(PipelineSegmentDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(PipelineSegmentDialog.accept)
        self.buttonBox.rejected.connect(PipelineSegmentDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PipelineSegmentDialog)
        PipelineSegmentDialog.setTabOrder(self.tabWidget, self.segment_no_edit)
        PipelineSegmentDialog.setTabOrder(self.segment_no_edit, self.length_edit)
        PipelineSegmentDialog.setTabOrder(self.length_edit, self.installation_date_chbox)
        PipelineSegmentDialog.setTabOrder(self.installation_date_chbox, self.installation_date_edit)
        PipelineSegmentDialog.setTabOrder(self.installation_date_edit, self.inspection_interval_sbox)
        PipelineSegmentDialog.setTabOrder(self.inspection_interval_sbox, self.inspection_interval_unit_cbox)
        PipelineSegmentDialog.setTabOrder(self.inspection_interval_unit_cbox, self.date_of_last_inspection_chbox)
        PipelineSegmentDialog.setTabOrder(self.date_of_last_inspection_chbox, self.date_of_last_inspection_edit)
        PipelineSegmentDialog.setTabOrder(self.date_of_last_inspection_edit, self.operating_state_cbox)
        PipelineSegmentDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        PipelineSegmentDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        PipelineSegmentDialog.setTabOrder(self.status_change_date_edit, self.network_cbox)
        PipelineSegmentDialog.setTabOrder(self.network_cbox, self.pipeline_type_cbox)
        PipelineSegmentDialog.setTabOrder(self.pipeline_type_cbox, self.mounting_type_cbox)
        PipelineSegmentDialog.setTabOrder(self.mounting_type_cbox, self.material_cbox)
        PipelineSegmentDialog.setTabOrder(self.material_cbox, self.placement_type_cbox)
        PipelineSegmentDialog.setTabOrder(self.placement_type_cbox, self.nominal_width_cbox)
        PipelineSegmentDialog.setTabOrder(self.nominal_width_cbox, self.positional_accuracy_cbox)
        PipelineSegmentDialog.setTabOrder(self.positional_accuracy_cbox, self.outside_diameter_sbox)
        PipelineSegmentDialog.setTabOrder(self.outside_diameter_sbox, self.wall_thickness_sbox)
        PipelineSegmentDialog.setTabOrder(self.wall_thickness_sbox, self.height_at_start_sbox)
        PipelineSegmentDialog.setTabOrder(self.height_at_start_sbox, self.height_at_end_sbox)
        PipelineSegmentDialog.setTabOrder(self.height_at_end_sbox, self.buttonBox)

    def retranslateUi(self, PipelineSegmentDialog):
        _translate = QtCore.QCoreApplication.translate
        PipelineSegmentDialog.setWindowTitle(_translate("PipelineSegmentDialog", "Add / Edit Pipeline Segment"))
        self.installation_date_edit.setDisplayFormat(_translate("PipelineSegmentDialog", "yyyy-MM-dd"))
        self.label_2.setText(_translate("PipelineSegmentDialog", "Calculated Length [m]"))
        self.label_3.setText(_translate("PipelineSegmentDialog", "Installation Date"))
        self.label_5.setText(_translate("PipelineSegmentDialog", "Inspection Interval"))
        self.label.setText(_translate("PipelineSegmentDialog", "Segment Number"))
        self.label_6.setText(_translate("PipelineSegmentDialog", "Inspection Interval Unit"))
        self.label_7.setText(_translate("PipelineSegmentDialog", "Operating State"))
        self.status_change_date_edit.setDisplayFormat(_translate("PipelineSegmentDialog", "yyyy-MM-dd"))
        self.label_8.setText(_translate("PipelineSegmentDialog", "Date of Status Change"))
        self.label_9.setText(_translate("PipelineSegmentDialog", "Pipeline Type"))
        self.label_10.setText(_translate("PipelineSegmentDialog", "Mounting Type"))
        self.label_11.setText(_translate("PipelineSegmentDialog", "Material"))
        self.label_12.setText(_translate("PipelineSegmentDialog", "Placement Type"))
        self.label_13.setText(_translate("PipelineSegmentDialog", "Nominal Width"))
        self.label_14.setText(_translate("PipelineSegmentDialog", "Outside Diameter [mm]"))
        self.label_15.setText(_translate("PipelineSegmentDialog", "Network"))
        self.label_17.setText(_translate("PipelineSegmentDialog", "Positional Accuracy"))
        self.label_18.setText(_translate("PipelineSegmentDialog", "Wall Thickness [mm]"))
        self.label_19.setText(_translate("PipelineSegmentDialog", "Height At Begin [m]"))
        self.label_20.setText(_translate("PipelineSegmentDialog", "Height At End [m]"))
        self.date_of_last_inspection_edit.setDisplayFormat(_translate("PipelineSegmentDialog", "yyyy-MM-dd"))
        self.label_21.setText(_translate("PipelineSegmentDialog", "Date of last inspection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PipelineSegmentDialog", "Description"))

from . import resources_rc
