# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './view/UtilityStationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UtilityStationDialog(object):
    def setupUi(self, UtilityStationDialog):
        UtilityStationDialog.setObjectName("UtilityStationDialog")
        UtilityStationDialog.resize(588, 450)
        UtilityStationDialog.setMinimumSize(QtCore.QSize(588, 450))
        UtilityStationDialog.setMaximumSize(QtCore.QSize(588, 480))
        self.buttonBox = QtWidgets.QDialogButtonBox(UtilityStationDialog)
        self.buttonBox.setGeometry(QtCore.QRect(405, 400, 166, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(UtilityStationDialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 10, 556, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.station_number_edit = QtWidgets.QLineEdit(self.tab)
        self.station_number_edit.setGeometry(QtCore.QRect(20, 30, 196, 20))
        self.station_number_edit.setObjectName("station_number_edit")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 15, 126, 16))
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 240, 126, 16))
        self.label_7.setObjectName("label_7")
        self.operating_state_cbox = QtWidgets.QComboBox(self.tab)
        self.operating_state_cbox.setGeometry(QtCore.QRect(20, 255, 196, 22))
        self.operating_state_cbox.setObjectName("operating_state_cbox")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(270, 16, 126, 16))
        self.label_9.setObjectName("label_9")
        self.purpose_cbox = QtWidgets.QComboBox(self.tab)
        self.purpose_cbox.setGeometry(QtCore.QRect(270, 31, 196, 22))
        self.purpose_cbox.setObjectName("purpose_cbox")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(270, 60, 126, 16))
        self.label_11.setObjectName("label_11")
        self.station_type_cbox = QtWidgets.QComboBox(self.tab)
        self.station_type_cbox.setGeometry(QtCore.QRect(270, 75, 196, 22))
        self.station_type_cbox.setObjectName("station_type_cbox")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(270, 105, 126, 16))
        self.label_12.setObjectName("label_12")
        self.location_cbox = QtWidgets.QComboBox(self.tab)
        self.location_cbox.setGeometry(QtCore.QRect(270, 120, 196, 22))
        self.location_cbox.setObjectName("location_cbox")
        self.height_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.height_sbox.setGeometry(QtCore.QRect(270, 165, 196, 22))
        self.height_sbox.setMinimum(-100.0)
        self.height_sbox.setMaximum(2000.0)
        self.height_sbox.setObjectName("height_sbox")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(270, 150, 126, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(270, 195, 126, 16))
        self.label_15.setObjectName("label_15")
        self.network_cbox = QtWidgets.QComboBox(self.tab)
        self.network_cbox.setGeometry(QtCore.QRect(270, 210, 196, 22))
        self.network_cbox.setObjectName("network_cbox")
        self.station_name_edit = QtWidgets.QLineEdit(self.tab)
        self.station_name_edit.setGeometry(QtCore.QRect(20, 75, 196, 20))
        self.station_name_edit.setObjectName("station_name_edit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 126, 16))
        self.label_2.setObjectName("label_2")
        self.installation_year_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.installation_year_sbox.setGeometry(QtCore.QRect(20, 120, 196, 22))
        self.installation_year_sbox.setDecimals(0)
        self.installation_year_sbox.setMaximum(3000.0)
        self.installation_year_sbox.setProperty("value", 0.0)
        self.installation_year_sbox.setObjectName("installation_year_sbox")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 105, 126, 16))
        self.label_16.setObjectName("label_16")
        self.capacity_sbox = QtWidgets.QDoubleSpinBox(self.tab)
        self.capacity_sbox.setGeometry(QtCore.QRect(20, 165, 196, 22))
        self.capacity_sbox.setMinimum(0.0)
        self.capacity_sbox.setMaximum(200000.0)
        self.capacity_sbox.setObjectName("capacity_sbox")
        self.capacity_unit_cbox = QtWidgets.QComboBox(self.tab)
        self.capacity_unit_cbox.setGeometry(QtCore.QRect(20, 210, 196, 22))
        self.capacity_unit_cbox.setObjectName("capacity_unit_cbox")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(20, 150, 126, 16))
        self.label_17.setObjectName("label_17")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(20, 195, 126, 16))
        self.label_13.setObjectName("label_13")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(19, 285, 126, 16))
        self.label_8.setObjectName("label_8")
        self.status_change_date_chbox = QtWidgets.QCheckBox(self.tab)
        self.status_change_date_chbox.setGeometry(QtCore.QRect(19, 305, 26, 17))
        self.status_change_date_chbox.setText("")
        self.status_change_date_chbox.setObjectName("status_change_date_chbox")
        self.status_change_date_edit = QtWidgets.QDateEdit(self.tab)
        self.status_change_date_edit.setEnabled(False)
        self.status_change_date_edit.setGeometry(QtCore.QRect(44, 300, 171, 22))
        self.status_change_date_edit.setCalendarPopup(True)
        self.status_change_date_edit.setObjectName("status_change_date_edit")
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(UtilityStationDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(UtilityStationDialog.accept)
        self.buttonBox.rejected.connect(UtilityStationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(UtilityStationDialog)
        UtilityStationDialog.setTabOrder(self.tabWidget, self.station_number_edit)
        UtilityStationDialog.setTabOrder(self.station_number_edit, self.station_name_edit)
        UtilityStationDialog.setTabOrder(self.station_name_edit, self.installation_year_sbox)
        UtilityStationDialog.setTabOrder(self.installation_year_sbox, self.capacity_sbox)
        UtilityStationDialog.setTabOrder(self.capacity_sbox, self.capacity_unit_cbox)
        UtilityStationDialog.setTabOrder(self.capacity_unit_cbox, self.operating_state_cbox)
        UtilityStationDialog.setTabOrder(self.operating_state_cbox, self.status_change_date_chbox)
        UtilityStationDialog.setTabOrder(self.status_change_date_chbox, self.status_change_date_edit)
        UtilityStationDialog.setTabOrder(self.status_change_date_edit, self.purpose_cbox)
        UtilityStationDialog.setTabOrder(self.purpose_cbox, self.station_type_cbox)
        UtilityStationDialog.setTabOrder(self.station_type_cbox, self.location_cbox)
        UtilityStationDialog.setTabOrder(self.location_cbox, self.height_sbox)
        UtilityStationDialog.setTabOrder(self.height_sbox, self.network_cbox)

    def retranslateUi(self, UtilityStationDialog):
        _translate = QtCore.QCoreApplication.translate
        UtilityStationDialog.setWindowTitle(_translate("UtilityStationDialog", "Add / Edit Utility Station"))
        self.label.setText(_translate("UtilityStationDialog", "Station Number"))
        self.label_7.setText(_translate("UtilityStationDialog", "Operating State"))
        self.label_9.setText(_translate("UtilityStationDialog", "Purpose"))
        self.label_11.setText(_translate("UtilityStationDialog", "Station Type"))
        self.label_12.setText(_translate("UtilityStationDialog", "Location"))
        self.label_14.setText(_translate("UtilityStationDialog", "Height [m]"))
        self.label_15.setText(_translate("UtilityStationDialog", "Network"))
        self.label_2.setText(_translate("UtilityStationDialog", "Station Name"))
        self.label_16.setText(_translate("UtilityStationDialog", "Installation Year"))
        self.label_17.setText(_translate("UtilityStationDialog", "Capacity"))
        self.label_13.setText(_translate("UtilityStationDialog", "Capacity Unit"))
        self.label_8.setText(_translate("UtilityStationDialog", "Date of Status Change"))
        self.status_change_date_edit.setDisplayFormat(_translate("UtilityStationDialog", "yyyy-MM-dd"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("UtilityStationDialog", "Description"))

from . import resources_rc
